### PR TITLE
Support renaming current workspace on long press

### PR DESCRIPTION
**Pull request by karypid**
Can you have a look at this with regard to issue #4 ?

### CODE REVIEW

**Comment by ahmafi** [comment]
This looks great, I wanted to test a few changes on top of your PR, can you enable [Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), so I can check my changes with you before merging?

**Comment by karypid** [comment]
This seems to already be checked. Are you unable to commit on top of the PR?

**Comment by ahmafi** [comment]
I don't know why I can't push on top of this PR. I'll add my changes after this.
I'm going to add a timeout, so the long press gets activated before releasing the mouse.
There is also a bug in your `_setActiveWorkspaceName`. If you change the second workspace name before the first one has a value, it doesn't work.

I have already created these changes and I will add them tomorrow.

Thanks for the contribution, I really liked the idea and your work.

**Comment by karypid** [comment]
Thank you, I have removed my fork. I'm wondering if the issue was due to me raising a PR against main branch directly? Usually I'd branch in he fork to /issues/N and raise PRs from that branch...

Anyway, looking forward to version 4 now!

**Pull request merged**
